"""In-memory mock data for UI/UX demo. No database required."""

from datetime import datetime, timezone
from werkzeug.security import generate_password_hash

# ── Users ──────────────────────────────────────────────────────────────
USERS = {
    'u1': {
        '_id': 'u1',
        'email': 'traveler@demo.com',
        'password': generate_password_hash('password'),
        'role': 'traveler',
        'profile': {
            'firstName': 'Alex',
            'lastName': 'Johnson',
            'phone': '+1 555-0100',
            'avatar': '',
            'address': {'street': '123 Main St', 'city': 'New York', 'state': 'NY', 'country': 'USA', 'zipCode': '10001'},
        },
        'preferences': {'currency': 'USD', 'language': 'en', 'notifications': True},
        'isActive': True,
    },
    'u2': {
        '_id': 'u2',
        'email': 'vendor@demo.com',
        'password': generate_password_hash('password'),
        'role': 'vendor',
        'profile': {
            'firstName': 'Sarah',
            'lastName': 'Williams',
            'phone': '+1 555-0200',
            'avatar': '',
            'address': {'street': '456 Oak Ave', 'city': 'San Francisco', 'state': 'CA', 'country': 'USA', 'zipCode': '94102'},
        },
        'preferences': {'currency': 'USD', 'language': 'en', 'notifications': True},
        'vendor': {
            'companyName': 'Wanderlust Adventures',
            'description': 'Premium travel experiences worldwide',
            'logo': '',
            'verified': True,
            'documents': [],
            'bankDetails': None,
        },
        'isActive': True,
    },
}

# ── Packages ───────────────────────────────────────────────────────────
PACKAGES = {
    'p1': {
        '_id': 'p1',
        'vendorId': 'u2',
        'title': 'Magical Bali Adventure',
        'slug': 'magical-bali-adventure',
        'description': 'Discover the enchanting island of Bali with its ancient temples, lush rice terraces, stunning beaches, and vibrant culture. This carefully curated package takes you through the best of Bali from the cultural heart of Ubud to the pristine shores of Nusa Dua.',
        'highlights': ['Visit ancient Uluwatu Temple at sunset', 'Trek through Tegallalang rice terraces', 'Snorkeling in crystal-clear waters', 'Traditional Balinese cooking class', 'Luxury spa treatment included'],
        'category': 'adventure',
        'destinations': [
            {'name': 'Ubud', 'duration': 3},
            {'name': 'Seminyak', 'duration': 2},
            {'name': 'Nusa Dua', 'duration': 2},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrival in Ubud', 'description': 'Welcome to Bali! Transfer to your luxury villa in Ubud.', 'activities': ['Airport pickup', 'Check-in at villa', 'Welcome dinner'], 'meals': {'breakfast': False, 'lunch': False, 'dinner': True}, 'accommodation': 'Ubud Luxury Villa'},
            {'day': 2, 'title': 'Temples & Rice Terraces', 'description': 'Explore the cultural heart of Bali.', 'activities': ['Tegallalang Rice Terrace trek', 'Tirta Empul water temple', 'Ubud Art Market'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Ubud Luxury Villa'},
            {'day': 3, 'title': 'Ubud Adventures', 'description': 'Action-packed day in and around Ubud.', 'activities': ['White water rafting on Ayung River', 'Monkey Forest sanctuary', 'Balinese cooking class'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Ubud Luxury Villa'},
            {'day': 4, 'title': 'Transfer to Seminyak', 'description': 'Move to the vibrant coastal area.', 'activities': ['Tanah Lot Temple visit', 'Transfer to Seminyak', 'Beach sunset walk'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': True}, 'accommodation': 'Seminyak Beach Resort'},
            {'day': 5, 'title': 'Seminyak Beach Day', 'description': 'Relax and explore the coast.', 'activities': ['Surfing lesson', 'Beach club lunch', 'Spa treatment'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': False}, 'accommodation': 'Seminyak Beach Resort'},
            {'day': 6, 'title': 'Nusa Dua Paradise', 'description': 'Transfer to the luxury resort area.', 'activities': ['Transfer to Nusa Dua', 'Snorkeling excursion', 'Water sports'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Nusa Dua Resort'},
            {'day': 7, 'title': 'Departure', 'description': 'Final morning in paradise.', 'activities': ['Sunrise yoga', 'Farewell breakfast', 'Airport transfer'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 1299, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [{'minSize': 4, 'discount': 10}, {'minSize': 8, 'discount': 15}], 'seasonalPricing': []},
        'inclusions': ['Luxury accommodation (6 nights)', 'Daily breakfast', 'Airport transfers', 'English-speaking guide', 'All entrance fees', 'Cooking class', 'Spa treatment', 'Snorkeling equipment'],
        'exclusions': ['International flights', 'Travel insurance', 'Personal expenses', 'Visa fees'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800', 'alt': 'Bali Temple', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800', 'alt': 'Rice Terraces', 'isPrimary': False},
            {'url': 'https://images.unsplash.com/photo-1573790387438-4da905039392?w=800', 'alt': 'Bali Beach', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-03-01', 'endDate': '2026-12-31', 'blackoutDates': [], 'maxGroupSize': 12, 'minGroupSize': 1},
        'duration': {'days': 7, 'nights': 6},
        'difficulty': 'moderate',
        'rating': {'average': 4.8, 'count': 24},
        'status': 'published',
        'featured': True,
        'tags': ['bali', 'indonesia', 'adventure', 'beach', 'culture'],
        'createdAt': datetime(2025, 6, 1, tzinfo=timezone.utc),
    },
    'p2': {
        '_id': 'p2',
        'vendorId': 'u2',
        'title': 'Swiss Alps Explorer',
        'slug': 'swiss-alps-explorer',
        'description': 'Experience the breathtaking beauty of the Swiss Alps with this premium tour. Journey through scenic mountain villages, ride iconic trains, and hike pristine alpine trails with panoramic views of snow-capped peaks and crystal-clear lakes.',
        'highlights': ['Ride the Glacier Express', 'Hike to Matterhorn viewpoint', 'Visit Jungfraujoch — Top of Europe', 'Cheese fondue experience', 'Lake Lucerne boat cruise'],
        'category': 'adventure',
        'destinations': [
            {'name': 'Lucerne', 'duration': 2},
            {'name': 'Interlaken', 'duration': 2},
            {'name': 'Zermatt', 'duration': 2},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrival in Lucerne', 'description': 'Arrive in the charming lakeside city.', 'activities': ['Airport transfer', 'Old Town walking tour', 'Chapel Bridge visit'], 'meals': {'breakfast': False, 'lunch': False, 'dinner': True}, 'accommodation': 'Lucerne Hotel'},
            {'day': 2, 'title': 'Mt. Pilatus & Lake Cruise', 'description': 'Explore the mountain and lake.', 'activities': ['Mt. Pilatus cable car', 'Alpine panorama views', 'Lake Lucerne boat cruise'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Lucerne Hotel'},
            {'day': 3, 'title': 'Interlaken Adventure', 'description': 'Transfer to the adventure capital.', 'activities': ['Scenic train to Interlaken', 'Paragliding (optional)', 'Harder Kulm viewpoint'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': True}, 'accommodation': 'Interlaken Hotel'},
            {'day': 4, 'title': 'Jungfraujoch', 'description': 'Visit the Top of Europe.', 'activities': ['Train to Jungfraujoch', 'Ice Palace', 'Sphinx Observatory'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Interlaken Hotel'},
            {'day': 5, 'title': 'Zermatt & Matterhorn', 'description': 'Journey to the iconic peak.', 'activities': ['Glacier Express to Zermatt', 'Village exploration', 'Matterhorn sunset views'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Zermatt Chalet'},
            {'day': 6, 'title': 'Departure', 'description': 'Final morning in the Alps.', 'activities': ['Gornergrat railway (optional)', 'Departure transfer'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 2499, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [{'minSize': 4, 'discount': 10}], 'seasonalPricing': []},
        'inclusions': ['5-star accommodation (5 nights)', 'Daily breakfast', 'Glacier Express tickets', 'Jungfraujoch tickets', 'All transfers', 'Mountain guide'],
        'exclusions': ['International flights', 'Travel insurance', 'Optional activities', 'Personal expenses'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800', 'alt': 'Swiss Alps', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=800', 'alt': 'Matterhorn', 'isPrimary': False},
            {'url': 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800', 'alt': 'Swiss Village', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-04-01', 'endDate': '2026-10-31', 'blackoutDates': [], 'maxGroupSize': 10, 'minGroupSize': 2},
        'duration': {'days': 6, 'nights': 5},
        'difficulty': 'moderate',
        'rating': {'average': 4.9, 'count': 18},
        'status': 'published',
        'featured': True,
        'tags': ['switzerland', 'alps', 'mountains', 'hiking', 'trains'],
        'createdAt': datetime(2025, 5, 15, tzinfo=timezone.utc),
    },
    'p3': {
        '_id': 'p3',
        'vendorId': 'u2',
        'title': 'Romantic Paris Getaway',
        'slug': 'romantic-paris-getaway',
        'description': 'Fall in love with the City of Light on this romantic Parisian escape. From the Eiffel Tower to Montmartre, experience world-class cuisine, art, and timeless charm in one of the most beautiful cities on Earth.',
        'highlights': ['Eiffel Tower dinner', 'Louvre Museum guided tour', 'Seine River sunset cruise', 'Montmartre walking tour', 'Wine & cheese tasting'],
        'category': 'honeymoon',
        'destinations': [{'name': 'Paris', 'duration': 5}],
        'itinerary': [
            {'day': 1, 'title': 'Bonjour Paris', 'description': 'Arrive and settle into the city of light.', 'activities': ['Airport transfer', 'Champs-Élysées stroll', 'Welcome dinner at bistro'], 'meals': {'breakfast': False, 'lunch': False, 'dinner': True}, 'accommodation': 'Boutique Hotel Le Marais'},
            {'day': 2, 'title': 'Art & Culture', 'description': 'Immerse in Parisian art.', 'activities': ['Louvre Museum guided tour', 'Tuileries Garden walk', 'Musée d\'Orsay'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': False}, 'accommodation': 'Boutique Hotel Le Marais'},
            {'day': 3, 'title': 'Iconic Paris', 'description': 'Visit the most iconic landmarks.', 'activities': ['Eiffel Tower visit', 'Seine River cruise', 'Dinner at Eiffel Tower restaurant'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': True}, 'accommodation': 'Boutique Hotel Le Marais'},
            {'day': 4, 'title': 'Montmartre & More', 'description': 'Explore charming neighborhoods.', 'activities': ['Montmartre walking tour', 'Sacré-Cœur Basilica', 'Wine & cheese tasting'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Boutique Hotel Le Marais'},
            {'day': 5, 'title': 'Au Revoir', 'description': 'Final morning in Paris.', 'activities': ['Pastry-making class', 'Departure transfer'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 1899, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [], 'seasonalPricing': []},
        'inclusions': ['Boutique hotel (4 nights)', 'Daily breakfast', 'Louvre guided tour', 'Seine cruise tickets', 'Eiffel Tower dinner', 'All transfers'],
        'exclusions': ['International flights', 'Travel insurance', 'Personal shopping'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800', 'alt': 'Eiffel Tower', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800', 'alt': 'Paris Streets', 'isPrimary': False},
            {'url': 'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=800', 'alt': 'Louvre Museum', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-01-01', 'endDate': '2026-12-31', 'blackoutDates': [], 'maxGroupSize': 6, 'minGroupSize': 2},
        'duration': {'days': 5, 'nights': 4},
        'difficulty': 'easy',
        'rating': {'average': 4.7, 'count': 32},
        'status': 'published',
        'featured': True,
        'tags': ['paris', 'france', 'romantic', 'honeymoon', 'culture'],
        'createdAt': datetime(2025, 7, 1, tzinfo=timezone.utc),
    },
    'p4': {
        '_id': 'p4',
        'vendorId': 'u2',
        'title': 'Kerala Backwaters & Wildlife',
        'slug': 'kerala-backwaters-wildlife',
        'description': 'Explore God\'s Own Country — Kerala. Cruise the serene backwaters on a traditional houseboat, spot wildlife at Periyar National Park, and relax on pristine Varkala cliffs overlooking the Arabian Sea.',
        'highlights': ['Houseboat stay on backwaters', 'Periyar Tiger Reserve safari', 'Ayurvedic spa treatment', 'Tea plantation tour in Munnar', 'Kathakali dance performance'],
        'category': 'wildlife',
        'destinations': [
            {'name': 'Munnar', 'duration': 2},
            {'name': 'Periyar', 'duration': 2},
            {'name': 'Alleppey', 'duration': 2},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Munnar', 'description': 'Drive up into the misty tea hills.', 'activities': ['Airport pickup from Kochi', 'Scenic drive to Munnar', 'Tea Museum visit'], 'meals': {'breakfast': False, 'lunch': True, 'dinner': True}, 'accommodation': 'Munnar Hillside Resort'},
            {'day': 2, 'title': 'Tea Country', 'description': 'Explore the lush plantations.', 'activities': ['Tea plantation guided walk', 'Eravikulam National Park', 'Mattupetty Dam'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Munnar Hillside Resort'},
            {'day': 3, 'title': 'Periyar Wilderness', 'description': 'Into the wild.', 'activities': ['Drive to Periyar', 'Spice plantation tour', 'Kathakali performance'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Periyar Lodge'},
            {'day': 4, 'title': 'Tiger Reserve', 'description': 'Full day safari.', 'activities': ['Morning boat safari', 'Nature trek', 'Ayurvedic massage'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Periyar Lodge'},
            {'day': 5, 'title': 'Backwaters Cruise', 'description': 'Board your private houseboat.', 'activities': ['Drive to Alleppey', 'Board houseboat', 'Cruise through backwaters'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Premium Houseboat'},
            {'day': 6, 'title': 'Departure', 'description': 'Morning on the water.', 'activities': ['Sunrise on backwaters', 'Disembark', 'Transfer to Kochi airport'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 899, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [{'minSize': 4, 'discount': 12}], 'seasonalPricing': []},
        'inclusions': ['All accommodation', 'Daily meals', 'Private houseboat', 'Safari & park fees', 'Ayurvedic treatment', 'All transfers'],
        'exclusions': ['Flights', 'Travel insurance', 'Tips', 'Personal expenses'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800', 'alt': 'Kerala Backwaters', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800', 'alt': 'Munnar Tea', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-01-01', 'endDate': '2026-12-31', 'blackoutDates': [], 'maxGroupSize': 8, 'minGroupSize': 2},
        'duration': {'days': 6, 'nights': 5},
        'difficulty': 'easy',
        'rating': {'average': 4.6, 'count': 15},
        'status': 'published',
        'featured': True,
        'tags': ['kerala', 'india', 'wildlife', 'backwaters', 'nature'],
        'createdAt': datetime(2025, 8, 1, tzinfo=timezone.utc),
    },
    'p5': {
        '_id': 'p5',
        'vendorId': 'u2',
        'title': 'Tokyo & Kyoto Cultural Journey',
        'slug': 'tokyo-kyoto-cultural-journey',
        'description': 'Immerse yourself in the fascinating contrast of Japan — from the neon-lit streets of Tokyo to the ancient temples of Kyoto. Experience tea ceremonies, bullet train rides, and the finest sushi on the planet.',
        'highlights': ['Bullet train Tokyo → Kyoto', 'Traditional tea ceremony', 'Tsukiji outer market food tour', 'Fushimi Inari shrine hike', 'Geisha district walking tour'],
        'category': 'cultural',
        'destinations': [
            {'name': 'Tokyo', 'duration': 3},
            {'name': 'Kyoto', 'duration': 3},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Welcome to Tokyo', 'description': 'Arrive in the world\'s largest metropolis.', 'activities': ['Airport transfer', 'Shibuya crossing', 'Welcome ramen dinner'], 'meals': {'breakfast': False, 'lunch': False, 'dinner': True}, 'accommodation': 'Shinjuku Hotel'},
            {'day': 2, 'title': 'Modern Tokyo', 'description': 'Explore the futuristic side of Tokyo.', 'activities': ['Tsukiji food tour', 'Senso-ji Temple', 'Akihabara district', 'TeamLab Borderless'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': False}, 'accommodation': 'Shinjuku Hotel'},
            {'day': 3, 'title': 'Traditional Tokyo', 'description': 'Discover old Edo.', 'activities': ['Meiji Shrine', 'Harajuku walk', 'Imperial Palace gardens'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': True}, 'accommodation': 'Shinjuku Hotel'},
            {'day': 4, 'title': 'Bullet Train to Kyoto', 'description': 'Ride the legendary Shinkansen.', 'activities': ['Shinkansen experience', 'Kinkaku-ji Golden Pavilion', 'Nishiki Market'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Kyoto Ryokan'},
            {'day': 5, 'title': 'Ancient Kyoto', 'description': 'Temples and traditions.', 'activities': ['Fushimi Inari sunrise hike', 'Bamboo Grove walk', 'Tea ceremony experience', 'Gion district evening walk'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Kyoto Ryokan'},
            {'day': 6, 'title': 'Sayonara', 'description': 'Final morning in Japan.', 'activities': ['Arashiyama morning', 'Departure transfer'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 2199, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [{'minSize': 4, 'discount': 8}], 'seasonalPricing': []},
        'inclusions': ['Hotel & ryokan (5 nights)', 'Bullet train tickets', 'Food tours', 'Temple entrance fees', 'Tea ceremony', 'All transfers'],
        'exclusions': ['International flights', 'Travel insurance', 'Personal shopping'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800', 'alt': 'Tokyo Tower', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800', 'alt': 'Kyoto Temple', 'isPrimary': False},
            {'url': 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800', 'alt': 'Fushimi Inari', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-03-01', 'endDate': '2026-11-30', 'blackoutDates': [], 'maxGroupSize': 10, 'minGroupSize': 1},
        'duration': {'days': 6, 'nights': 5},
        'difficulty': 'easy',
        'rating': {'average': 4.9, 'count': 41},
        'status': 'published',
        'featured': True,
        'tags': ['japan', 'tokyo', 'kyoto', 'culture', 'food'],
        'createdAt': datetime(2025, 4, 1, tzinfo=timezone.utc),
    },
    'p6': {
        '_id': 'p6',
        'vendorId': 'u2',
        'title': 'Maldives Beach Escape',
        'slug': 'maldives-beach-escape',
        'description': 'Unwind in absolute paradise. Crystal-clear turquoise waters, overwater villas, and world-class snorkeling — the Maldives is the ultimate tropical escape for couples and families alike.',
        'highlights': ['Overwater villa with glass floor', 'Sunset dolphin cruise', 'Underwater restaurant dinner', 'Private sandbank picnic', 'Coral reef snorkeling'],
        'category': 'beach',
        'destinations': [{'name': 'Maldives', 'duration': 5}],
        'itinerary': [
            {'day': 1, 'title': 'Arrival in Paradise', 'description': 'Seaplane transfer to your private island.', 'activities': ['Seaplane to resort', 'Villa check-in', 'Welcome cocktails'], 'meals': {'breakfast': False, 'lunch': True, 'dinner': True}, 'accommodation': 'Overwater Villa'},
            {'day': 2, 'title': 'Ocean Adventures', 'description': 'Explore the underwater world.', 'activities': ['Snorkeling trip', 'Kayaking', 'Spa treatment'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Overwater Villa'},
            {'day': 3, 'title': 'Island Experiences', 'description': 'Unique Maldivian experiences.', 'activities': ['Dolphin cruise', 'Sandbank picnic', 'Sunset fishing'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Overwater Villa'},
            {'day': 4, 'title': 'Pure Relaxation', 'description': 'A day of pure bliss.', 'activities': ['Morning yoga', 'Beach day', 'Underwater restaurant dinner'], 'meals': {'breakfast': True, 'lunch': True, 'dinner': True}, 'accommodation': 'Overwater Villa'},
            {'day': 5, 'title': 'Farewell', 'description': 'Last sunrise in paradise.', 'activities': ['Sunrise swim', 'Departure transfer'], 'meals': {'breakfast': True, 'lunch': False, 'dinner': False}, 'accommodation': ''},
        ],
        'pricing': {'basePrice': 3499, 'currency': 'USD', 'perPersonPrice': True, 'groupDiscounts': [], 'seasonalPricing': []},
        'inclusions': ['Overwater villa (4 nights)', 'Full board meals', 'Seaplane transfers', 'Snorkeling gear', 'Dolphin cruise', 'Spa treatment'],
        'exclusions': ['International flights', 'Scuba diving course', 'Premium drinks'],
        'images': [
            {'url': 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800', 'alt': 'Maldives Overwater', 'isPrimary': True},
            {'url': 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800', 'alt': 'Maldives Beach', 'isPrimary': False},
        ],
        'videos': [],
        'availability': {'startDate': '2026-01-01', 'endDate': '2026-12-31', 'blackoutDates': [], 'maxGroupSize': 4, 'minGroupSize': 2},
        'duration': {'days': 5, 'nights': 4},
        'difficulty': 'easy',
        'rating': {'average': 4.9, 'count': 28},
        'status': 'published',
        'featured': True,
        'tags': ['maldives', 'beach', 'luxury', 'honeymoon', 'snorkeling'],
        'createdAt': datetime(2025, 3, 1, tzinfo=timezone.utc),
    },
}

# ── Bookings ───────────────────────────────────────────────────────────
BOOKINGS = {
    'b1': {
        '_id': 'b1',
        'bookingId': 'TRP-2026-10001',
        'packageId': 'p1',
        'userId': 'u1',
        'vendorId': 'u2',
        'travelers': [
            {'name': 'Alex Johnson', 'age': 30, 'gender': 'male'},
            {'name': 'Jamie Johnson', 'age': 28, 'gender': 'female'},
        ],
        'travelDates': {'start': '2026-04-15', 'end': '2026-04-21'},
        'totalAmount': 2598.00,
        'currency': 'USD',
        'payment': {'status': 'completed', 'method': 'stripe', 'transactionId': 'pi_demo123', 'paidAmount': 2598.00, 'refundAmount': 0, 'history': []},
        'status': 'confirmed',
        'specialRequests': 'Vegetarian meals please',
        'cancellation': None,
        'createdAt': datetime(2026, 1, 10, tzinfo=timezone.utc),
        'updatedAt': datetime(2026, 1, 10, tzinfo=timezone.utc),
    },
    'b2': {
        '_id': 'b2',
        'bookingId': 'TRP-2026-10002',
        'packageId': 'p3',
        'userId': 'u1',
        'vendorId': 'u2',
        'travelers': [
            {'name': 'Alex Johnson', 'age': 30, 'gender': 'male'},
        ],
        'travelDates': {'start': '2026-06-01', 'end': '2026-06-05'},
        'totalAmount': 1899.00,
        'currency': 'USD',
        'payment': {'status': 'pending', 'method': None, 'transactionId': None, 'paidAmount': 0, 'refundAmount': 0, 'history': []},
        'status': 'pending',
        'specialRequests': '',
        'cancellation': None,
        'createdAt': datetime(2026, 2, 1, tzinfo=timezone.utc),
        'updatedAt': datetime(2026, 2, 1, tzinfo=timezone.utc),
    },
    'b3': {
        '_id': 'b3',
        'bookingId': 'TRP-2025-10003',
        'packageId': 'p5',
        'userId': 'u1',
        'vendorId': 'u2',
        'travelers': [
            {'name': 'Alex Johnson', 'age': 30, 'gender': 'male'},
            {'name': 'Jamie Johnson', 'age': 28, 'gender': 'female'},
        ],
        'travelDates': {'start': '2025-10-10', 'end': '2025-10-15'},
        'totalAmount': 4398.00,
        'currency': 'USD',
        'payment': {'status': 'completed', 'method': 'stripe', 'transactionId': 'pi_demo456', 'paidAmount': 4398.00, 'refundAmount': 0, 'history': []},
        'status': 'completed',
        'specialRequests': 'Anniversary trip!',
        'cancellation': None,
        'createdAt': datetime(2025, 9, 1, tzinfo=timezone.utc),
        'updatedAt': datetime(2025, 10, 15, tzinfo=timezone.utc),
    },
}

# ── Reviews ────────────────────────────────────────────────────────────
REVIEWS = {
    'r1': {
        '_id': 'r1',
        'packageId': 'p1',
        'userId': 'u1',
        'bookingId': 'b1',
        'rating': 5,
        'title': 'Absolutely incredible experience!',
        'content': 'The Bali adventure exceeded all our expectations. The rice terrace trek was breathtaking, and the cooking class was so much fun. Our guide was knowledgeable and friendly. The luxury villa in Ubud was pure bliss. Highly recommend this package!',
        'images': [],
        'helpfulCount': 12,
        'vendorReply': {'content': 'Thank you so much, Alex! It was a pleasure hosting you and Jamie. We hope to welcome you back to Bali soon! 🌴', 'repliedAt': datetime(2026, 1, 20, tzinfo=timezone.utc)},
        'status': 'approved',
        'createdAt': datetime(2026, 1, 15, tzinfo=timezone.utc),
    },
    'r2': {
        '_id': 'r2',
        'packageId': 'p5',
        'userId': 'u1',
        'bookingId': 'b3',
        'rating': 5,
        'title': 'Japan blew our minds!',
        'content': 'From the bustling streets of Tokyo to the serene temples of Kyoto, every moment was magical. The bullet train experience alone was worth it. The tea ceremony was such a unique cultural experience. The ryokan in Kyoto was amazing.',
        'images': [],
        'helpfulCount': 8,
        'vendorReply': None,
        'status': 'approved',
        'createdAt': datetime(2025, 10, 20, tzinfo=timezone.utc),
    },
    'r3': {
        '_id': 'r3',
        'packageId': 'p1',
        'userId': 'u1',
        'bookingId': 'b1',
        'rating': 4,
        'title': 'Great trip with minor hiccups',
        'content': 'Overall a wonderful experience. The snorkeling was fantastic and the temples were beautiful. Only giving 4 stars because the transfer from Ubud to Seminyak took longer than expected. But the vendor handled it well.',
        'images': [],
        'helpfulCount': 3,
        'vendorReply': None,
        'status': 'approved',
        'createdAt': datetime(2025, 12, 5, tzinfo=timezone.utc),
    },
}

# ── AI Itineraries (sample) ───────────────────────────────────────────
AI_ITINERARIES = {}

# ── Counters ───────────────────────────────────────────────────────────
_next_id = {'package': 7, 'booking': 4, 'review': 4, 'user': 3, 'ai': 1}


def next_id(entity):
    n = _next_id[entity]
    _next_id[entity] = n + 1
    return f'{entity[0]}{n}'
